apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-analytics-demo.fullname" . }}
  labels:
{{ include "video-analytics-demo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "video-analytics-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "video-analytics-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-1"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - sh
          - -c
          - {{ .Values.command.appname}} -c {{ .Values.command.apparg }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8554
              protocol: TCP
            - name: http1
              containerPort: {{ .Values.service.webuiPort }}
              protocol: TCP
          volumeMounts:
            - name: x11unix
              mountPath: /tmp/.X11-unix
            - name: argus-volume
              mountPath: /tmp/argus_socket
      volumes:
        - name: x11unix
          hostPath:
            path: /tmp/.X11-unix
        - name: argus-volume
          hostPath:
            path: /tmp/argus_socket
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

