apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-path
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - nolock
  nfs:
    path: {{ .Values.image.modelRepositoryPath }}
    server: localhost